myfoodsite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
  path('',views.IndexClassView.as_view(),name='home'),
  path('item/',views.item,name='item'),
  path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
  #add items
  path('add/',views.CreateItem.as_view(),name='create_item'),
  #edit
  path('update/<int:id>',views.update_item,name='update_item'),
  #delete
  path('delete/<int:id>',views.delete_item, name='delete_item'),
]

myfoodsite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import RegisterForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html',), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html',), name='logout'),
    path('profile/',user_views.profile_page,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfoodsite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Item(models.Model):
  def __str__(self):
    return self.item_name
  user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
  item_name = models.CharField(max_length=200)
  item_desc = models.CharField(max_length=200)
  item_price = models.IntegerField()
  item_image = models.CharField(max_length=500,default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

  def get_absolute_url(self):
    return reverse("food:detail", kwargs={"pk":self.pk})

myfoodsite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
  location = models.CharField(max_length=100)

  def __str__(self):
    return self.user.username

myfoodsite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']

myfoodsite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username','email','password1','password2']

myfoodsite/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.


def index(request):
  item_list = Item.objects.all()
  context = {
    'item_list':item_list,
  }
  return render(request,'food/index.html',context)

class IndexClassView(ListView):
  model = Item;
  template_name = 'food/index.html'
  contaxt_object_name = 'item_list'


def item(request):
  return HttpResponse('This is an item view')

def detail(request,item_id):
  item = Item.objects.get(pk=item_id)
  context = {
    'item':item,
  }
  return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
  model = Item
  template_name = 'food/detail.html'


def create_item(request):
  form = ItemForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('food:home')
  return render(request, 'food/item-form.html', {'form':form})

class CreateItem(CreateView):
  model = Item
  fields = ['item_name','item_desc','item_price','item_image']
  template_name = 'food/item-form.html'
  def form_valid(self,form):
    form.instance.user_name = self.request.user
    return super().form_valid(form)

  
def update_item(request,id):
  item = Item.objects.get(id=id)
  form = ItemForm(request.POST or None, instance=item)

  if form.is_valid():
    form.save()
    return redirect('food:home')
  return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
  item = Item.objects.get(id=id)
  if request.method == 'POST':
    item.delete()
    return redirect('food:home')
  return render(request,'food/item-delete.html',{'item':item})
  

myfoodsite/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login
# Create your views here.


def register(request):
  if request.method == 'POST':
    form = RegisterForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request,f'Welcome {username},your account is created!')
      return redirect('login')
  else:
    form = RegisterForm()
  return render(request,'users/register.html',{'form':form})


@login_required
def profile_page(request):
  return render(request,'users/profile.html')

myfoodsite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'food/style.css' %}">
  {% block head %}
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <title>Base</title>
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">FoodApp</a>
    <div class="navbar">
      <a href="{% url 'food:create_item' %}" class="nav-item nav-link text-light">Add Item</a>
      <a href="#" class="nav-item nav-link text-light">Delete Item</a>
      <a href="#" class="nav-item nav-link text-light">View Item</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="nav-item nav-link text-light">Logout</a>
        <a href="{% url 'profile' %}">Profile</a>
      {% else %}
        <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tag }}">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
{% block base %}
  
{% endblock %}
</body>
</html>

myfoodsite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block base %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="{{ item.item_image }}" class="card">
    </div>
    <div class="col-md-6">
      <h1>{{ object.item_name }}</h1>
      <h2>{{ object.item_desc }}</h2>
      <h3>${{ object.item_price }}</h3>
      
      <a href="{% url 'food:delete_item' item.id %}">Delete</a>
    </div>
  </div>
</div>
{% endblock %}

myfoodsite/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block base %}
{% for item in item_list %}
<div class="row">
  <div class="col-md-3 offset-md-2">
    <img src="{{ item.item_image }}" style="width:auto;height:150px;" class="card">
  </div>
  <div class="col-md-4">
    <h3>{{ item.item_name }}</h3>
    <h5>{{ item.item_desc }}</h5>
    <h6>${{ item.item_price }}</h6>
    <p>Author: {{ item.user_name }}</p>
  </div>
  <div class="col-md-2">
    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
  </div>
</div>
{% endfor %}
{% endblock %}

myfoodsite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block base %}
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want ot delete? {{ item.item_name }}</h2>
  <button type="submit">Confirm</button>
</form>
{% endblock %}

myfoodsite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% load widget_tweaks %}


{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'styleLogin.css' %}">
{% endblock %}

{% block base %}

<div class="form-container">
  <p class="title">Add item</p>
	<form class="form" method="POST">
    {% csrf_token %}
		<div class="input-group">
			<label for="item_name">item's name</label>
      {{ form.item_name }}
		</div>
    <div class="input-group">
			<label for="item_desc">item's description</label>
      {{ form.item_desc }}
		</div>
		<div class="input-group">
			<label for="item_price">item's price</label>
      {{ form.item_price }}
		</div>
    <div class="input-group">
			<label for="item_image">item's image URL</label>
      {{ form.item_image }}
		</div>
		<button class="sign">Add</button>
  </form>
</div>

{% endblock %}

myfoodsite/users/templates/users/login.html
{% extends 'food/base.html' %}
{% load widget_tweaks %}


{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'styleLogin.css' %}">
{% endblock %}

{% block base %}
<div class="form-container">
	<p class="title">Login</p>
	<form method="POST" class="form">
    {% csrf_token %}
		<div class="input-group">
			<label for="username">Username</label>
      		{{ form.username|add_class:"control" }}
		</div>
		<div class="input-group">
			<label for="password">Password</label>
      		{{ form.password }}
		</div>
		<button type="submit" class="sign">Login</button>
	</form>
</div>


{% endblock %}

myfoodsite/users/templates/users/logout.html
<h1>You have been logged out!</h1>

myfoodsite/users/templates/users/profile.html
<h1>{{ user.username }}</h1>

<img src="{{ user.profile.image.url }}" width="100px">

myfoodsite/users/templates/users/register.html
{% extends 'food/base.html' %}
{% load widget_tweaks %}


{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'styleLogin.css' %}">
{% endblock %}

{% block base %}

<div class="form-container">
  <p class="title">Sign up</p>
	<form class="form" method="POST">
    {% csrf_token %}
		<div class="input-group">
			<label for="username">Username</label>
      {{ form.username }}
		</div>
    <div class="input-group">
			<label for="email">Email</label>
      {{ form.email }}
		</div>
		<div class="input-group">
			<label for="password1">Password</label>
      {{ form.password1 }}
		</div>
    <div class="input-group">
			<label for="password2">Confirm Password</label>
      {{ form.password2 }}
		</div>
		<button class="sign">Sign in</button>
  </form>
</div>

{% endblock %}